<?xml version="1.0" encoding="UTF-8"?>
<testsuite name="Login Test"
           tests="4"
           failures="2"
           errors="0"
           skipped="0"
           time="119.692">
  <properties />
            <testcase name="verifyUserIsAbleToLoginSuccessfully" time="3.689" classname="com.demo.nopcommerce.testsuite.LoginTestWithExcelData">
                <failure type="java.lang.AssertionError"
                  message="The following asserts failed:
	expected [Welcome to our store] but found [About login / registration],
	expected [Welcome to our store] but found [About login / registration]"
              >
<![CDATA[java.lang.AssertionError: The following asserts failed:
	expected [Welcome to our store] but found [About login / registration],
	expected [Welcome to our store] but found [About login / registration]
  org.testng.asserts.SoftAssert.assertAll(SoftAssert.java:47)
  org.testng.asserts.SoftAssert.assertAll(SoftAssert.java:31)
  com.demo.nopcommerce.testsuite.LoginTestWithExcelData.verifyUserIsAbleToLoginSuccessfully(LoginTestWithExcelData.java:68)
  sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
  sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
  sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
  java.lang.reflect.Method.invoke(Method.java:498)
  org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:134)
  org.testng.internal.TestInvoker.invokeMethod(TestInvoker.java:597)
  org.testng.internal.TestInvoker.invokeTestMethod(TestInvoker.java:173)
  org.testng.internal.MethodRunner.runInSequence(MethodRunner.java:46)
  org.testng.internal.TestInvoker$MethodInvocationAgent.invoke(TestInvoker.java:816)
  org.testng.internal.TestInvoker.invokeTestMethods(TestInvoker.java:146)
  org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:146)
  org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:128)
  java.util.ArrayList.forEach(ArrayList.java:1249)
  org.testng.TestRunner.privateRun(TestRunner.java:766)
  org.testng.TestRunner.run(TestRunner.java:587)
  org.testng.SuiteRunner.runTest(SuiteRunner.java:384)
  org.testng.SuiteRunner.runSequentially(SuiteRunner.java:378)
  org.testng.SuiteRunner.privateRun(SuiteRunner.java:337)
  org.testng.SuiteRunner.run(SuiteRunner.java:286)
  org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:53)
  org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:96)
  org.testng.TestNG.runSuitesSequentially(TestNG.java:1187)
  org.testng.TestNG.runSuitesLocally(TestNG.java:1109)
  org.testng.TestNG.runSuites(TestNG.java:1039)
  org.testng.TestNG.run(TestNG.java:1007)
  com.intellij.rt.testng.IDEARemoteTestNG.run(IDEARemoteTestNG.java:66)
  com.intellij.rt.testng.RemoteTestNGStarter.main(RemoteTestNGStarter.java:110)
]]>
      </failure>

          </testcase>
            <testcase name="verifyUserIsAbleToLoginSuccessfully" time="5.463" classname="com.demo.nopcommerce.testsuite.LoginTestWithExcelData">
                <failure type="java.lang.AssertionError"
                  message="The following asserts failed:
	expected [Welcome to our store] but found [About login / registration]"
              >
<![CDATA[java.lang.AssertionError: The following asserts failed:
	expected [Welcome to our store] but found [About login / registration]
  org.testng.asserts.SoftAssert.assertAll(SoftAssert.java:47)
  org.testng.asserts.SoftAssert.assertAll(SoftAssert.java:31)
  com.demo.nopcommerce.testsuite.LoginTestWithExcelData.verifyUserIsAbleToLoginSuccessfully(LoginTestWithExcelData.java:68)
  sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
  sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
  sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
  java.lang.reflect.Method.invoke(Method.java:498)
  org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:134)
  org.testng.internal.TestInvoker.invokeMethod(TestInvoker.java:597)
  org.testng.internal.TestInvoker.invokeTestMethod(TestInvoker.java:173)
  org.testng.internal.MethodRunner.runInSequence(MethodRunner.java:46)
  org.testng.internal.TestInvoker$MethodInvocationAgent.invoke(TestInvoker.java:816)
  org.testng.internal.TestInvoker.invokeTestMethods(TestInvoker.java:146)
  org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:146)
  org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:128)
  java.util.ArrayList.forEach(ArrayList.java:1249)
  org.testng.TestRunner.privateRun(TestRunner.java:766)
  org.testng.TestRunner.run(TestRunner.java:587)
  org.testng.SuiteRunner.runTest(SuiteRunner.java:384)
  org.testng.SuiteRunner.runSequentially(SuiteRunner.java:378)
  org.testng.SuiteRunner.privateRun(SuiteRunner.java:337)
  org.testng.SuiteRunner.run(SuiteRunner.java:286)
  org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:53)
  org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:96)
  org.testng.TestNG.runSuitesSequentially(TestNG.java:1187)
  org.testng.TestNG.runSuitesLocally(TestNG.java:1109)
  org.testng.TestNG.runSuites(TestNG.java:1039)
  org.testng.TestNG.run(TestNG.java:1007)
  com.intellij.rt.testng.IDEARemoteTestNG.run(IDEARemoteTestNG.java:66)
  com.intellij.rt.testng.RemoteTestNGStarter.main(RemoteTestNGStarter.java:110)
]]>
      </failure>

          </testcase>
  
  
            <testcase name="verifyUserIsAbleToLoginSuccessfully" time="55.283" classname="com.demo.nopcommerce.testsuite.LoginTestWithExcelData" />
                <testcase name="verifyUserIsAbleToLoginSuccessfully" time="55.257" classname="com.demo.nopcommerce.testsuite.LoginTestWithExcelData" />
      
</testsuite>
